version: 2.1

references:

  install_deps: &install_deps
    run:
      name: Install dependencies
      command: |
        sudo apt-get update && sudo apt-get install -y cmake
        pip install "$TORCH_VERSION"
        pip install flake8

  flake8_test: &flake8_test
    run:
      name: flake8 compatibility
      command: |
        pip install flake8
        flake8 .

  build_pkg: &build_pkg
    run:
      name: Build package
      command: |
        pip install .[dev]
        python setup.py clean

  build_docs: &build_docs
    run:
      name: Build docs
      command: |
        sudo apt-get install pandoc
        sphinx-build docs/ docs/_build

  tests: &tests
    run:
      name: Test suite
      command: |
        pytest tests/ --cov=gradslam

  send_cov: &send_cov
    run:
      name: Send coverage
      when: on_success
      command: |
        bash <(curl -s https://codecov.io/bash)

jobs:

  PyTorch:
    docker:
      - image: circleci/python:3.6
    environment:
      - TORCH_VERSION: "torch==1.6"
    steps: &steps
      - checkout
      - *flake8_test
      - *install_deps
      - *build_pkg
      - *build_docs
      - *tests
      - *send_cov

workflows:
  version: 2.1
  build:
    jobs:
      - PyTorch
